In [4]:
def isnum(n):
    n=str(n)
    if n.isdigit():
        return True
    return False
li = ["10","20","a"]
a = map(isnum,li)
list(a)

[True, True, False]

In [6]:
a = filter(isnum,li)
list(a)


['10', '20']

## ***Lambda*** ##

In [8]:
def sum1(a,b):
    c=a+b
    return c
sum1(12,8)

20

In [10]:
a= lambda x,y:x+y
a(34,7)

41

In [13]:
a = lambda x: x**2
a(4)

16

# ***List Comprehension*** #

In [15]:
a = int(input())
for i in range(0,a+1):
    print(i**2)

5
0
1
4
9
16
25


In [17]:
a = [i**2 for i in range(1,11)]
a

[1, 4, 9, 16, 25, 36, 49, 64, 81, 100]

In [28]:
def factorial(n):
    fact = 1
    for i in range(1,n+1):
        fact=fact*i
    print("the factorialof",n,"is",fact)
    
        

In [29]:
factorial(9)

the factorialof 9 is 362880


In [31]:
a = int(input())
b =1
for i in range(1,a+1):
    b *=i
print(b)

438
291465358436857445699990619809052867265667058392638441238329604026154747355237080816451970309983750337663191048914563034675050254717927784458749572977103982340410569761653435074373821687910354665927211506727769963410800918926590685286068376492670496286397087879722215412942659986997662686673441766406446672366736534295997891473983424697262517912371252721883375279701590819475700513365717949536474726056153589078210360155948794063067075770047303463559429535385015459613156925884058564632386299366982430894440624534347364322618902782487738575388622506948907810775855795812128948497735878828214214654885839768457331875526631317911734396712702631041269438963669618769825640343884874777489549183945852077263191073740496915347935663314015977298934736403243025542377241693123103842352540666402152595378107793232521225697460469709891227831468422580413020294298119385907200000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000


In [1]:
import math
s=[math.factorial(i)for i in range(1,10)]
s

[1, 2, 6, 24, 120, 720, 5040, 40320, 362880]

# *File Handling*

 * Performing operations on a file is called file handling
 * Entering some data to a file is called as write to a file
 * Retrieving data from a file is called aws reading from a file
 * We can perform append,delete operations on files

In [16]:
def writetoafile(filename,data):
    with open(filename,"w")as f:
        fd = f.write (data)
    return 
filename = "data.txt"
writetoafile(filename,"line 1\n line 2\n")

In [15]:
def readfromafile(filename):
    with open(filename,"r")as f:
        fd = f.read()
        f.close()
    return fd
readfromafile("data.txt")

'line 1\n line 2\n'

In [23]:
def readfromafile(filename):
    with open(filename,"r")as f:
        fd = f.read()
        
    return fd
filename = "data,txt"
readfromafile("data.txt")
def printlines(filename):
    with open (filename,"r")as f:
        for line in f:
            print(line,end="")
    return
print(readfromafile(filename))
        
        

FileNotFoundError: [Errno 2] No such file or directory: 'data,txt'

In [26]:
def appendtofile(filename,data):
    with open(filename,"a")as f:
        for line in data:
            f.write("\n"+line)
        return
data = ["line3","line4","line5","line6"]
filename = "data.txt"
appendtofile(filename,data)

# ***Numpy*** 

 * ***Numpy is an advantage libraray***.
 * ***Numpy --- numerical python***
 * ***Numpy is to perform mathematical and stastical operations***
 * ***The values are represented in the for of row and columns***
 

### ***Adavntages of numpy when comper to list***

* ***It take less time***
* ***performance will be high***
* ***occpies less memory***

In [1]:
import numpy as np

In [2]:
###creat an array using in numpy
a= np.array([1,3,4,5])
a

array([1, 3, 4, 5])

In [3]:
a= np.array([1,3,4,5])
a.size

4

In [5]:
###creat an array in praticular range
a = np.arange(1,20)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19])

In [6]:
###check the numbers of elements
a.size

19

In [7]:
a+1

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
       19, 20])

In [8]:
a-1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18])

In [9]:
a*2

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34,
       36, 38])

In [11]:
a2 = np.array([[1,2,3,4],[5,6,7,8]])
a2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [12]:
a2.size

8

In [14]:
a3 = np.array([[1,2,3,4],[5,6,7,8]],dtype = complex)
a3

array([[1.+0.j, 2.+0.j, 3.+0.j, 4.+0.j],
       [5.+0.j, 6.+0.j, 7.+0.j, 8.+0.j]])

In [15]:
a3.dtype

dtype('complex128')

In [16]:
a.dtype

dtype('int32')

In [17]:
np.arange

<function numpy.arange>

In [ ]:
### comparision of two arrays

a1 = np.arange(2,5) + np.arange

In [19]:
a = np.array([[1,2,3,4],[6,7,8,9]])
b = np.array([[9,8,7,6],[5,4,3,2]])

In [20]:
a>b

array([[False, False, False, False],
       [ True,  True,  True,  True]])

In [21]:
a<b

array([[ True,  True,  True,  True],
       [False, False, False, False]])

In [22]:
a+b

array([[10, 10, 10, 10],
       [11, 11, 11, 11]])

In [23]:
a-b

array([[-8, -6, -4, -2],
       [ 1,  3,  5,  7]])

In [24]:
a*b

array([[ 9, 16, 21, 24],
       [30, 28, 24, 18]])

In [25]:
a**b

array([[   1,  256, 2187, 4096],
       [7776, 2401,  512,   81]], dtype=int32)

In [26]:
b**a

array([[    9,    64,   343,  1296],
       [15625, 16384,  6561,   512]], dtype=int32)

In [27]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [28]:
np.ones(5,dtype = int)

array([1, 1, 1, 1, 1])

In [30]:
np.ones([5,4],dtype = int)

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [31]:
np.zeros([3,4],dtype=int)

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [32]:
a[0]

array([1, 2, 3, 4])

In [33]:
a[0:1,1:2]   ### a[starting row:ending row,startingcolumn:ending]

array([[2]])

In [34]:
a[1:2,2:3]

array([[8]])

In [35]:
a

array([[1, 2, 3, 4],
       [6, 7, 8, 9]])

In [36]:
a[:,1:3]

array([[2, 3],
       [7, 8]])

In [37]:
a[:,2:3]

array([[3],
       [8]])

In [42]:
a[:,0:2]

array([[1, 2],
       [6, 7]])

In [39]:
a.shape

(2, 4)

In [40]:
a.ndim

2

In [43]:
a.itemsize

4

In [52]:
a[:,1:2]

array([[2],
       [7]])

In [46]:
b = np.arange(3,9)
b

array([3, 4, 5, 6, 7, 8])

In [48]:
b = np.arange(3,9)
b.reshape(1,6)

array([[3, 4, 5, 6, 7, 8]])

In [49]:
b = np.arange(3,9)
b.reshape(6,1)

array([[3],
       [4],
       [5],
       [6],
       [7],
       [8]])

In [50]:
b.reshape(2,3)

array([[3, 4, 5],
       [6, 7, 8]])

In [53]:
max(b)

8

In [55]:
np.mean(b)

5.5

In [56]:
np.std(b)

1.707825127659933

In [57]:
np.sum(b)

33

In [58]:
np.var(b)

2.9166666666666665

In [59]:
np.cumsum(b)

array([ 3,  7, 12, 18, 25, 33], dtype=int32)

In [60]:
np.argmax(b)

5

In [61]:
np.argmin(b)

0

In [62]:
np.transpose(b)

array([3, 4, 5, 6, 7, 8])

In [63]:
b=a

# ***decimal to binary***

In [76]:
def decimaltobinary(n):
    if n>1:
        decimaltobinary(n//2)
    print(n%2,end='')
n =(int(input("enter number")))
decimaltobinary(n)
    

enter number39
100111

# ***binary to decimal*** #

In [65]:
b=(int(input("enter nuumber")))
d = 0
i = 0
while b!=0:
    binary = b%10
    d = d+binary*(2**i)
    b=b//10
    i=i+1
print(d)

enter nuumber0111
7
